apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/id-microservice/spring-env-vars:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/id-microservice/spring-env-vars:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-env-vars
        chartPath: charts/spring-env-vars
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/id-microservice/spring-env-vars"
          image.tag: "{{.TAG}}"
